import random

NICHES = {
    "bhakti": {
        "keywords": [
            "Hindu God AI Animation", 
            "Mahadev 3D Cinematic", 
            "Lord Krishna AI Divine",
            "Sanatan Dharma AI Art",
            "Lord Ram 4K Cinematic AI",
            "Hanuman 3D Animation",
            "Ganesha AI Cinematic",
            "Maa Durga AI Animation",
            "Vedic Stories Cinematic AI",
            "Spiritual Soul Meditation AI",
            "Shiv tandav AI cinematic",
            "Bajrangbali power cinematic",
            "Krishna leela AI shorts",
            "Ram bhakti AI animation",
            "Bhagavad Gita verse shorts",
            "Sanatan truth shorts",
            "Durga mata divine visuals",
            "Radha Krishna devotion cinematic",
            "Temple energy AI reels",
            "Bhakti motivation shorts",
            "Hindu religious story shorts",
            "Ramayan short story AI",
            "Mahabharat story shorts",
            "Shiv puran story reels",
            "Krishna story shorts",
            "Hanuman story cinematic",
            "Vishnu avatar story shorts",
            "Ancient hindu story animation",
            "Sanatan kahani shorts",
            "Dharmik kahani viral shorts",
            "Hindu God status",
            "Mahadev status viral",
            "Krishna bhajan status",
            "Hanuman chalisa shorts",
            "Ram bhakti status trending",
            "Sanatan Dharma status",
            "Kedarnath status viral",
            "Ujjain Mahakal status",
            "Vrindavan Krishna status",
            "Ayodhya Ram Mandir status",
            "Bhakti reels viral",
            "Religious motivational shorts",
            "Hindu mythology stories",
            "Ramayan status",
            "Mahabharat status"
        ],
        "trending_keywords": [
            "hanuman bhakti status viral",
            "mahadev status trending",
            "krishna bhajan shorts viral",
            "jai shree ram shorts trending",
            "sanatan dharma reels viral",
            "bholenath edit trending",
            "radhe radhe shorts viral",
            "hindu devotional shorts trending",
            "hanuman chalisa shorts trending",
            "mahakal status viral",
            "shree ram bhakti reels trending",
            "krishna motivation shorts viral",
            "sanatan edit reels trending",
            "shiv bhakti shorts viral",
            "hindu god ai video trending",
            "ramayan story shorts viral",
            "mahabharat story trending",
            "shiv puran shorts viral",
            "krishna story reels trending",
            "dharmik kahani shorts viral"
        ],
        "query_modifiers": [
            "viral 2026", "trending 2026", "april 2026", "latest viral", "current month trending",
            "reels trending", "status viral", "devotional shorts", "4k edit", "cinematic viral",
            "religious story", "hindu story", "dharmik kahani", "puran story", "epic story"
        ],
        "min_likes": 300,
        "min_views": 3000,
        "min_duration": 30,
        "max_duration": 65,
        "enable_segment_queue": True,
        "queue_min_source_duration": 70,
        "queue_part_min_duration": 35,
        "queue_part_max_duration": 40,
        "queue_max_parts": 3,
        "queue_search_queries": 32,
        "max_age_days": 45,
        "max_queries_per_run": 150,
        "search_timeout_seconds": 25,
        "download_timeout_seconds": 50,
        "min_topic_score": 1,
        "preferred_hours_ist": [7, 18, 21],
        "default_language": "hi",
        "default_audio_language": "hi",
        "series_formats": [
            "Aaj Ka Bhakti Rahasya",
            "Divine Signal",
            "Sanatan Truth",
            "Bhakti Power Short"
        ],
        "comment_templates": [
            "🙏 Agar bhakti mehsoos hui ho to comment mein 'Jai Shri Ram' likho.",
            "🔱 Agar aise aur divine shorts chahiye to comment mein 'Har Har Mahadev' likho.",
            "💛 Is series ka next part chahiye ho to comment mein 'Radhe Radhe' likho."
        ],
        "post_pinned_comment": True,
        "blacklist": ["face", "facecam", "selfie", "man talking", "woman talking", "person talking", "front camera"],
        "ai_prompt": "You are an expert Hindu devotional YouTube Shorts strategist. Create highly clickable Hindi metadata that matches the exact source video topic, uses emotionally strong but believable hooks, and is optimized for watch time, curiosity, CTR, and repeat views.",
        "fallbacks": [
            {"title": "आज ये देख लो! भगवान का चमत्कार 😱🙏 #Shorts", "description": "🙏 जय श्री राम! भगवान की कृपा आप पर सदा बनी रहे।"},
            {"title": "⚠️ ये गलती कभी मत करना! महादेव देख रहे हैं 🔱 #Shorts", "description": "🔱 हर हर महादेव! शिव जी के इस रहस्य को जानिए।"},
            {"title": "भगवान कृष्ण का ये संदेश आपका जीवन बदल देगा 🤯🕉️ #Shorts", "description": "💛 राधे राधे! श्री कृष्ण की अनमोल वाणी।"}
        ],
        "history_file": "download_history_bhakti.txt",
        "token_file": "token_bhakti.json",
        "token_secret": "YOUTUBE_TOKEN_JSON",
        "client_secret_file": "client_secret_bhakti.json"
    },
    "akonymous": {
        "keywords": [
            "Best movie clips 4K cinematic",
            "Emotional movie scenes vertical",
            "Action movie shorts HD",
            "Famous movie dialogues cinematic",
            "Mind-bending movie scenes",
            "Hollywood blockbuster clips",
            "Heart touching movie moments",
            "Intense cinema scenes",
            "Best movie shots 4K",
            "Iconic film scenes vertical",
            "Netflix series viral clips",
            "Movie quotes cinematic visuals",
            "Epic movie battle scenes",
            "Sad movie moments viral",
            "Thriller movie clips vertical"
        ],
        "trending_keywords": [
            "viral movie clips trending",
            "movie scenes 2026 trending",
            "cinema edit shorts viral",
            "hollywood status trending",
            "movie dialogue status reels",
            "intense movie scenes viral",
            "best movie scenes 4k shorts",
            "cinematic edit movie status",
            "epic movie clips trending",
            "hollywood movie shorts viral"
        ],
        "query_modifiers": [
            "viral 2026", "trending 2026", "april 2026", "latest viral", "current month trending",
            "shorts viral", "analysis", "documentary style", "hidden truth", "decoded", "evidence based"
        ],
        "min_likes": 200,
        "min_views": 2000,
        "min_duration": 45,
        "max_duration": 65,
        "enable_segment_queue": False,
        "max_age_days": 60,
        "max_queries_per_run": 150,
        "search_timeout_seconds": 20,
        "download_timeout_seconds": 45,
        "min_topic_score": 2,
        "preferred_hours_ist": [15, 19, 22],
        "default_language": "en",
        "default_audio_language": "en",
        "series_formats": [
            "AKONYMOUS Decode",
            "Hidden Pattern",
            "Signal Drop",
            "Reality Glitch"
        ],
        "comment_templates": [
            "Comment 'TRUTH' if you want part 2.",
            "If this made you think, comment 'DECODED'.",
            "Drop 'MORE' if you want the next hidden fact."
        ],
        "post_pinned_comment": True,
        "blacklist": ["face", "facecam", "selfie", "man talking", "woman talking", "person talking", "front camera"],
        "ai_prompt": "You are a cinema expert and YouTube Shorts strategist. Create highly clickable English metadata for famous movie clips. Focus on the emotional intensity, the characters, or the jaw-dropping moments. Your metadata must make the viewer feel the scene's impact immediately. Optimized for CTR, retention, and movie-buff engagement.",
        "fallbacks": [
            {"title": "This scene will give you chills... 🎬 #Shorts", "description": "Cinema at its absolute best. The emotion in this scene is unmatched.\n\n#MovieClips #Cinema #Epic"},
            {"title": "He didn't expect THIS to happen 😱 #Movie", "description": "One of the most intense moments in film history. Watch until the end.\n\n#Hollywood #Intense #Shorts"},
            {"title": "The most powerful dialogue ever? 🎤 #Cinema", "description": "Words that stayed with us forever. Pure cinematic gold.\n\n#Dialogues #BestScenes #Film"}
        ],
        "history_file": "download_history_akonymous.txt",
        "token_file": "token_akonymous.json",
        "token_secret": "YOUTUBE_TOKEN_JSON_AKONYMOUS",
        "client_secret_file": "client_secret.json"
    }
}

def get_config(niche_name):
    return NICHES.get(niche_name.lower(), NICHES["bhakti"])
